// Prefixos por categoria
const categoryPrefixes: Record<string, string> = {
  eletronicos: 'ELE',
  escritorio: 'ESC',
  limpeza: 'LIM',
  manutencao: 'MAN',
  cozinha: 'COZ',
  outros: 'OUT'
};

// Gera caracteres aleatorios (exclui caracteres confusos como O, 0, I, 1)
const generateRandomChars = (length: number): string => {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

// Retorna o prefixo da categoria
export const getCategoryPrefix = (category: string): string => {
  return categoryPrefixes[category] || 'OUT';
};

// Funcao principal de geracao de SKU
// Formato: [PREFIXO_CATEGORIA]-[YYMMDD]-[RANDOM]
// Exemplo: ELE-250127-A3F2
export const generateSKU = (
  category: string, 
  existingSKUs: Set<string>
): string => {
  const prefix = getCategoryPrefix(category);
  const date = new Date();
  const dateStr = `${String(date.getFullYear()).slice(-2)}${String(date.getMonth() + 1).padStart(2, '0')}${String(date.getDate()).padStart(2, '0')}`;
  
  let sku: string;
  let attempts = 0;
  const maxAttempts = 100;
  
  do {
    const random = generateRandomChars(4);
    sku = `${prefix}-${dateStr}-${random}`;
    attempts++;
  } while (existingSKUs.has(sku) && attempts < maxAttempts);
  
  // Adiciona ao set para evitar duplicatas na mesma sessao
  existingSKUs.add(sku);
  return sku;
};

// Verifica se um SKU foi gerado automaticamente pelo sistema
export const isAutoGeneratedSKU = (sku: string): boolean => {
  // Formato: XXX-YYMMDD-XXXX (3 letras, 6 numeros, 4 caracteres)
  const pattern = /^[A-Z]{3}-\d{6}-[A-Z0-9]{4}$/;
  return pattern.test(sku);
};
