import type { InstitutionalClass, InstitutionalSchedule } from '@/components/academico/InstitutionalScheduleGrid';
const c = (day: number, start: string, end: string, subject: string, professor?: string, room?: string): InstitutionalClass => ({ day, start, end, subject, professor, room });
const ead = (subject: string): InstitutionalClass => ({ day: 6, start: '00:00', end: '23:59', subject, professor: 'Ambiente Virtual', ead: true });

export const TEST_SCHEDULES: InstitutionalSchedule[] = [
  { course: 'Direito', classCode: 'DRM201', semester: '2º PERÍODO', academicPeriod: '2026.2', shift: 'MANHÃ', entries: [c(1, '07:10', '08:00', 'Teoria Geral do Direito', 'Profa. Ana Lúcia', 'Sala 204 / Bloco D'), c(1, '08:00', '08:50', 'Teoria Geral do Direito', 'Profa. Ana Lúcia', 'Sala 204 / Bloco D'), c(2, '07:10', '08:00', 'Direito Constitucional I', 'Prof. Marcelo Lima', 'Sala 108 / Bloco D'), c(3, '08:50', '09:40', 'Direito Civil I', 'Profa. Camila Souza', 'Sala 204 / Bloco D'), c(4, '07:10', '08:00', 'Ciência Política', 'Prof. Rafael Costa', 'Sala 108 / Bloco D'), c(5, '10:40', '11:30', 'Metodologia Científica', 'Profa. Juliana Reis', 'Sala 204 / Bloco D'), ead('Introdução ao Estudo do Direito')] },
  { course: 'Administração', classCode: 'ADM301', semester: '3º PERÍODO', academicPeriod: '2026.2', shift: 'TARDE', entries: [c(1, '13:10', '14:00', 'Gestão de Pessoas', 'Profa. Renata Alves', 'Sala 310 / Bloco A'), c(2, '14:50', '15:40', 'Contabilidade Geral', 'Prof. André Silva', 'Sala 310 / Bloco A'), c(3, '13:10', '14:00', 'Marketing I', 'Profa. Beatriz Melo', 'Sala 105 / Bloco A'), c(4, '15:50', '16:40', 'Economia Empresarial', 'Prof. Paulo Nunes', 'Sala 310 / Bloco A'), ead('Fundamentos de Administração')] },
  { course: 'Enfermagem', classCode: 'ENF102', semester: '1º PERÍODO', academicPeriod: '2026.2', shift: 'NOITE', entries: [c(1, '18:30', '19:20', 'Anatomia Humana', 'Profa. Kátia Lima', 'Laboratório 2'), c(2, '18:30', '19:20', 'Biologia Celular', 'Prof. Michel Souza', 'Sala 116 / Bloco B'), c(3, '20:20', '21:10', 'Diagnóstico em Saúde', 'Profa. Ana Lúcia', 'Sala 116 / Bloco B'), c(5, '20:20', '21:10', 'Bioquímica', 'Prof. André Luís', 'Laboratório 1'), ead('Direitos Humanos')] },
];
