import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ClipboardList, FlaskConical } from 'lucide-react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';

export default function ProcedimentosExames() {
  const qc = useQueryClient(); const [clinicId, setClinicId] = useState(''); const [patientId, setPatientId] = useState(''); const [procedureName, setProcedureName] = useState(''); const [examName, setExamName] = useState('');
  const data = useQuery({ queryKey: ['procedures-exams'], queryFn: async () => { const [clinics, patients, procedures, exams] = await Promise.all([supabase.from('clinics').select('id,organization_id,name').eq('is_active', true), supabase.from('patients').select('id,record_number,person:persons(full_name)').eq('status', 'active'), (supabase as any).from('clinical_procedures').select('id,name,status,created_at,clinic:clinics(name),patient:patients(record_number,person:persons(full_name))').is('archived_at', null).order('created_at', { ascending: false }).limit(40), (supabase as any).from('exam_orders').select('id,exam_name,status,requested_at,clinic:clinics(name),patient:patients(record_number,person:persons(full_name))').order('requested_at', { ascending: false }).limit(40)]); for (const result of [clinics, patients, procedures, exams]) if (result.error) throw result.error; return { clinics: clinics.data ?? [], patients: patients.data ?? [], procedures: procedures.data ?? [], exams: exams.data ?? [] }; } });
  const createProcedure = useMutation({ mutationFn: async () => { const clinic = (data.data?.clinics as any[]).find((item) => item.id === clinicId); if (!clinic || !patientId || !procedureName.trim()) throw new Error('Preencha clínica, paciente e procedimento.'); const { data: auth } = await supabase.auth.getUser(); const { error } = await (supabase as any).from('clinical_procedures').insert({ organization_id: clinic.organization_id, clinic_id: clinicId, patient_id: patientId, code: procedureName.trim().toUpperCase().replace(/\s+/g, '_'), name: procedureName.trim(), status: 'planned', created_by: auth.user?.id }); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['procedures-exams'] }); setProcedureName(''); toast({ title: 'Procedimento planejado' }); }, onError: (error: Error) => toast({ title: 'Não foi possível registrar', description: error.message, variant: 'destructive' }) });
  const createExam = useMutation({ mutationFn: async () => { const clinic = (data.data?.clinics as any[]).find((item) => item.id === clinicId); if (!clinic || !patientId || !examName.trim()) throw new Error('Preencha clínica, paciente e exame.'); const { data: auth } = await supabase.auth.getUser(); const { error } = await (supabase as any).from('exam_orders').insert({ organization_id: clinic.organization_id, clinic_id: clinicId, patient_id: patientId, exam_name: examName.trim(), status: 'requested', created_by: auth.user?.id }); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['procedures-exams'] }); setExamName(''); toast({ title: 'Exame solicitado' }); }, onError: (error: Error) => toast({ title: 'Não foi possível solicitar', description: error.message, variant: 'destructive' }) });
  const submit = (action: () => void) => (event: FormEvent) => { event.preventDefault(); action(); }; const clinics = (data.data?.clinics as any[]) ?? []; const patients = (data.data?.patients as any[]) ?? []; const procedures = (data.data?.procedures as any[]) ?? []; const exams = (data.data?.exams as any[]) ?? [];
  return <MainLayout><div className="space-y-6"><div className="flex gap-3"><div className="rounded-lg bg-primary/10 p-2"><ClipboardList className="h-6 w-6 text-primary" /></div><div><h1 className="text-2xl font-bold">Procedimentos e exames</h1><p className="text-sm text-muted-foreground">Registre condutas e solicitações vinculadas ao paciente, com status acompanhável.</p></div></div><Card><CardHeader><CardTitle className="text-base">Novo registro clínico</CardTitle><CardDescription>Selecione a clínica e o paciente para habilitar as ações.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2"><Picker label="Clínica" value={clinicId} setValue={setClinicId} options={clinics} text={(item: any) => item.name}/><Picker label="Paciente" value={patientId} setValue={setPatientId} options={patients} text={(item: any) => `${item.record_number} — ${item.person?.full_name ?? ''}`}/><form onSubmit={submit(() => createProcedure.mutate())} className="flex items-end gap-2"><div className="flex-1 space-y-1"><Label>Procedimento</Label><Input value={procedureName} onChange={(event) => setProcedureName(event.target.value)} placeholder="Ex.: Limpeza profilática" required /></div><Button disabled={!clinicId || !patientId || createProcedure.isPending}><ClipboardList className="mr-1 h-4 w-4" />Planejar</Button></form><form onSubmit={submit(() => createExam.mutate())} className="flex items-end gap-2"><div className="flex-1 space-y-1"><Label>Exame</Label><Input value={examName} onChange={(event) => setExamName(event.target.value)} placeholder="Ex.: Radiografia" required /></div><Button disabled={!clinicId || !patientId || createExam.isPending}><FlaskConical className="mr-1 h-4 w-4" />Solicitar</Button></form></div></CardContent></Card><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Procedimentos recentes</CardTitle></CardHeader><CardContent className="space-y-2">{procedures.length ? procedures.map((item: any) => <div key={item.id} className="flex items-center justify-between rounded border p-3 text-sm"><span>{item.name} · {item.patient?.person?.full_name ?? item.patient?.record_number}</span><Badge variant="outline">{item.status}</Badge></div>) : <p className="text-sm text-muted-foreground">Nenhum procedimento registrado.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Exames recentes</CardTitle></CardHeader><CardContent className="space-y-2">{exams.length ? exams.map((item: any) => <div key={item.id} className="flex items-center justify-between rounded border p-3 text-sm"><span>{item.exam_name} · {item.patient?.person?.full_name ?? item.patient?.record_number}</span><Badge variant="outline">{item.status}</Badge></div>) : <p className="text-sm text-muted-foreground">Nenhum exame solicitado.</p>}</CardContent></Card></div></div></MainLayout>;
}
function Picker({ label, value, setValue, options, text }: { label: string; value: string; setValue: (value: string) => void; options: any[]; text: (item: any) => string }) { return <div className="space-y-1"><Label>{label}</Label><Select value={value} onValueChange={setValue}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{options.map((item) => <SelectItem key={item.id} value={item.id}>{text(item)}</SelectItem>)}</SelectContent></Select></div>; }
