import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Cat, PawPrint } from 'lucide-react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';

export default function Veterinaria() {
  const qc = useQueryClient(); const [name, setName] = useState(''); const [species, setSpecies] = useState('Canina'); const [breed, setBreed] = useState(''); const [sex, setSex] = useState('unknown'); const [microchip, setMicrochip] = useState(''); const [guardianId, setGuardianId] = useState('');
  const data = useQuery({ queryKey: ['veterinary'], queryFn: async () => { const [animals, persons] = await Promise.all([(supabase as any).from('animals').select('id,name,species,breed,sex,microchip_number,animal_guardians(person:persons(full_name))').is('archived_at', null).order('name'), (supabase as any).from('persons').select('id,full_name').is('archived_at', null).order('full_name').limit(500)]); if (animals.error) throw animals.error; if (persons.error) throw persons.error; return { animals: animals.data ?? [], persons: persons.data ?? [] }; } });
  const create = useMutation({ mutationFn: async () => { if (!name.trim() || !guardianId) throw new Error('Informe o nome do animal e o tutor.'); const { data: org, error: orgError } = await supabase.from('organizations').select('id').limit(1).single(); if (orgError) throw orgError; const { data: auth } = await supabase.auth.getUser(); const { data: animal, error } = await (supabase as any).from('animals').insert({ organization_id: org.id, name: name.trim(), species, breed: breed.trim() || null, sex, microchip_number: microchip.trim() || null, created_by: auth.user?.id }).select('id').single(); if (error) throw error; const { error: guardianError } = await (supabase as any).from('animal_guardians').insert({ animal_id: animal.id, person_id: guardianId, relationship: 'tutor', is_primary: true, created_by: auth.user?.id }); if (guardianError) throw guardianError; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['veterinary'] }); setName(''); setBreed(''); setMicrochip(''); toast({ title: 'Animal cadastrado' }); }, onError: (error: Error) => toast({ title: 'Não foi possível cadastrar', description: error.message, variant: 'destructive' }) });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(); }; const animals = (data.data?.animals as any[]) ?? []; const persons = (data.data?.persons as any[]) ?? [];
  return <MainLayout><div className="space-y-6"><div className="flex gap-3"><div className="rounded-lg bg-primary/10 p-2"><PawPrint className="h-6 w-6 text-primary" /></div><div><h1 className="text-2xl font-bold">Clínica veterinária</h1><p className="text-sm text-muted-foreground">Cadastre animais e mantenha tutores vinculados ao cadastro mestre de pessoas.</p></div></div><div className="grid gap-5 lg:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle className="text-base">Novo animal</CardTitle><CardDescription>O tutor precisa estar cadastrado como pessoa.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-3"><div className="space-y-1"><Label>Nome</Label><Input value={name} onChange={(event) => setName(event.target.value)} required /></div><div className="space-y-1"><Label>Espécie</Label><Input value={species} onChange={(event) => setSpecies(event.target.value)} required /></div><div className="space-y-1"><Label>Raça</Label><Input value={breed} onChange={(event) => setBreed(event.target.value)} /></div><div className="space-y-1"><Label>Sexo</Label><Select value={sex} onValueChange={setSex}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="female">Fêmea</SelectItem><SelectItem value="male">Macho</SelectItem><SelectItem value="unknown">Não informado</SelectItem></SelectContent></Select></div><div className="space-y-1"><Label>Microchip</Label><Input value={microchip} onChange={(event) => setMicrochip(event.target.value)} /></div><div className="space-y-1"><Label>Tutor</Label><Select value={guardianId} onValueChange={setGuardianId}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{persons.map((person: any) => <SelectItem key={person.id} value={person.id}>{person.full_name}</SelectItem>)}</SelectContent></Select></div><Button disabled={create.isPending || !guardianId}>Cadastrar animal</Button></form></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Animais cadastrados</CardTitle></CardHeader><CardContent className="space-y-2">{animals.length ? animals.map((animal: any) => <div key={animal.id} className="flex items-center justify-between rounded border p-3"><div className="flex items-center gap-3"><Cat className="h-5 w-5 text-primary" /><div><div className="font-medium">{animal.name}</div><div className="text-sm text-muted-foreground">{animal.species}{animal.breed ? ` · ${animal.breed}` : ''} · tutor {animal.animal_guardians?.[0]?.person?.full_name ?? '—'}</div></div></div><Badge variant="outline">{animal.sex === 'female' ? 'Fêmea' : animal.sex === 'male' ? 'Macho' : '—'}</Badge></div>) : <p className="text-sm text-muted-foreground">Nenhum animal cadastrado.</p>}</CardContent></Card></div></div></MainLayout>;
}
