import { MapPin, ShieldCheck } from 'lucide-react';
import { MainLayout } from '@/components/layout/MainLayout';
import { useCanReadAcademic } from '@/components/academico/StaffOnly';
import { useAcademicMeetings } from '@/hooks/useAcademicSchedules';
import { AcademicMeetingTable } from '@/components/academico/AcademicMeetingTable';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function Ensalamento() { const canRead = useCanReadAcademic(); const { data: meetings = [], isLoading, error } = useAcademicMeetings(); if (!canRead) return <MainLayout><p className="text-sm text-muted-foreground">Sem permissão.</p></MainLayout>; const allocated = meetings.filter((item) => item.room).length; return <MainLayout><div className="space-y-6"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><MapPin className="h-6 w-6 text-primary" />Ensalamento</h1><p className="mt-1 text-sm text-muted-foreground">Distribuição de aulas por sala, com proteção de conflito no banco.</p></div><div className="grid gap-4 md:grid-cols-3"><Metric label="Aulas programadas" value={meetings.length} /><Metric label="Com sala alocada" value={allocated} /><Metric label="Pendentes" value={meetings.length - allocated} tone="warning" /></div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 text-emerald-600" />Validação transacional</CardTitle><CardDescription>Sobreposições de sala, professor e turma são rejeitadas pelo Supabase.</CardDescription></CardHeader><CardContent>{isLoading ? <p className="text-sm text-muted-foreground">Carregando ensalamento…</p> : error ? <p className="text-sm text-destructive">Não foi possível consultar as aulas.</p> : <AcademicMeetingTable meetings={meetings} />}</CardContent></Card></div></MainLayout>; }
function Metric({ label, value, tone }: { label: string; value: number; tone?: 'warning' }) { return <Card><CardContent className="p-5"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className={tone ? 'mt-2 text-3xl font-bold text-amber-600' : 'mt-2 text-3xl font-bold'}>{value}</p></CardContent></Card>; }
