-- Insert auth user for victordoui@gmail.com
INSERT INTO auth.users (
  instance_id, 
  id, 
  aud, 
  role, 
  email, 
  encrypted_password, 
  email_confirmed_at, 
  confirmation_sent_at, 
  recovery_sent_at, 
  email_change_sent_at, 
  new_email, 
  invited_at, 
  action_link, 
  email_change, 
  email_change_confirm_status, 
  banned_until, 
  raw_app_meta_data, 
  raw_user_meta_data, 
  is_super_admin, 
  created_at, 
  updated_at, 
  phone, 
  phone_confirmed_at, 
  phone_change, 
  phone_change_token, 
  phone_change_sent_at, 
  confirmed_at, 
  email_change_token_current, 
  email_change_token_new, 
  recovery_token, 
  reauthentication_token, 
  reauthentication_sent_at,
  is_anonymous
)
VALUES (
  '00000000-0000-0000-0000-000000000000',
  '181e1c43-b2d8-47af-838f-56891c3affd1',
  'authenticated',
  'authenticated',
  'victordoui@gmail.com',
  '$2a$10$ExampleHashForDevelopment123456789',
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  NULL,
  '',
  '',
  0,
  NULL,
  '{}',
  '{"provider": "email", "providers": ["email"]}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  NOW(),
  '',
  '',
  '',
  '',
  NULL,
  FALSE
)
ON CONFLICT (id) DO UPDATE SET
  email = EXCLUDED.email,
  updated_at = NOW(),
  email_confirmed_at = NOW(),
  confirmed_at = NOW();