// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onngvrefjnzwvxmqnztd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubmd2cmVmam56d3Z4bXFuenRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTA2MDIsImV4cCI6MjA3MzA4NjYwMn0.E1O_NiFp7W2C2zn7ZP28diAtzIGCUl-fSW-bMI4Dl-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});